config_file:
    /.mounts/labs/simpsonlab/users/schaudhary/code/strview/configs/DMPK_CTG_long_flank_plasmids.tsv

strique:
    /.mounts/labs/simpsonlab/users/schaudhary/projects/2020.11.STRDetection/STRique/scripts/STRique.py

strique_pore_model:
   /.mounts/labs/simpsonlab/users/jsimpson/projects/nanopore/2021.05.26.str_lengths/common/r9_4_450bps.model

bonito:
   /.mounts/labs/simpsonlab/sw/miniconda3/envs/bonito/bin/bonito

guppy5_fast:
    path: "/.mounts/labs/ont/software/guppy-5.0.11/bin/"
    mode: "fast"
    guppy_extra: ""

guppy5_hac:
    path: "/.mounts/labs/ont/software/guppy-5.0.11/bin/"
    mode: "hac"
    guppy_extra: ""

guppy5_super:
    path: "/.mounts/labs/ont/software/guppy-5.0.11/bin/"
    mode: "sup"
    guppy_extra: ""

guppy5_hac_modbases:
    path: "/.mounts/labs/ont/software/guppy-5.0.11/bin/"
    mode: "modbases_5mc_hac"
    guppy_extra: ""

guppy5_hac_modbases_as:
    path: "/.mounts/labs/ont/software/guppy-5.0.11/bin/"
    mode: "modbases_5mc_hac"
    guppy_extra: "--pt_scaling"

guppy5_hac_as:
    path: "/.mounts/labs/ont/software/guppy-5.0.11/bin/"
    mode: "hac"
    guppy_extra: "--pt_scaling"

guppy5_hac_cs5k:
    path: "/.mounts/labs/ont/software/guppy-5.0.11/bin/"
    mode: "hac"
    guppy_extra: "--chunk_size 5000"

bonito_fast:
    mode: "dna_r9.4.1_e8.1_fast@v3.4"

bonito_hac:
    mode: "dna_r9.4.1_e8.1_hac@v3.3"

bonito_super:
    mode: "dna_r9.4.1_e8.1_sup@v3.3"

basecall_configs: [ bonito_fast , bonito_hac, bonito_super ]

samples:
    [ c9orf72_singleplex ]

strique_reads_per_chunk: 2000

cn: 3
microsat: /.mounts/labs/simpsonlab/users/schaudhary/projects/2020.11.STRDetection/c9orf72_repeat.txt
summary: ""
fast5: /.mounts/labs/simpsonlab/data/yuen_lab_str_project/C9orf72_single_MK/fast5/

cell_line:
    reference: /.mounts/labs/simpsonlab/data/references/GRCh38_no_alt_analysis_set.GCA_000001405.15.fna
    strscore_config: /.mounts/labs/simpsonlab/users/schaudhary/code/strview/configs/c9orf72.strique.tsv
    strique_index: /.mounts/labs/simpsonlab/users/schaudhary/code/strview/index_dmpk_cell_line.fofn
    repeat_config: /.mounts/labs/simpsonlab/users/schaudhary/code/strview/configs/c9orf72.strique.tsv
    fast5: "/.mounts/labs/simpsonlab/data/yuen_lab_str_project/C9orf72_single_MK/fast5/"
    barcoding_kit: "none"
    graphaligner_mode: "--multiseed-DP 1"
    methods: [ "ga" , "simplecount" , "tg" ]
    maximum_length_for_plot: 1200
    cn: "3"
    microsat: /.mounts/labs/simpsonlab/users/schaudhary/projects/2020.11.STRDetection/c9orf72_repeat.txt

c9orf72_singleplex:
    fastq: "none"
    barcode: "none"
    data_type: "cell_line"
